name: lebenslauf
description: A Flutter project to create a CV for Marcus Wassermann.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/Mittel .png
    - assets/signature.png
    - assets/logo-transparent-png.png
    - assets/durchatmen.mp4
    - assets/bild.png
